//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees.DataAccessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePhoneNumber
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public string PhoneType { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
