//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees.DataAccessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAddress
    {
        public int AddressID { get; set; }
        public int EmployeeID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
